# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1680x1000")
window.configure(bg="#FFFFFF")


canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=1000,
    width=1680,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(840.0, 38.0, image=image_image_1)

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
)
button_1.place(
    x=784.5315551757811,
    y=12.782693862915096,
    width=327.7757568359375,
    height=52.000003814697266,
)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    40.999999999999886, 39.00000000000006, image=image_image_2
)

canvas.create_text(
    68.99999999999989,
    19.000000000000057,
    anchor="nw",
    text="PressureTumorAI",
    fill="#000000",
    font=("Avenir Black", 36 * -1),
)

button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
)
button_2.place(
    x=1158.303466796875, y=12.782693862915096, width=251.77684020996094, height=52.0
)

button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
)
button_3.place(
    x=1456.15283203125,
    y=12.782693862915096,
    width=196.42315673828125,
    height=50.18000411987305,
)

image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    338.9999999999999, 276.00000000000006, image=image_image_3
)

image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    921.9999999999999, 276.00000000000006, image=image_image_4
)

image_image_5 = PhotoImage(file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(1278.0, 688.0, image=image_image_5)

image_image_6 = PhotoImage(file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(1423.0, 277.00000000000006, image=image_image_6)

image_image_7 = PhotoImage(file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(199.0000000000001, 962.0, image=image_image_7)

image_image_8 = PhotoImage(file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(774.9999999999999, 962.0, image=image_image_8)

image_image_9 = PhotoImage(file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    233.04107666015614, 157.38093566894537, image=image_image_9
)

image_image_10 = PhotoImage(file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    237.0702438354491, 235.52381896972662, image=image_image_10
)

image_image_11 = PhotoImage(file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(439.9999999999999, 688.0, image=image_image_11)

canvas.create_text(
    335.9999999999999,
    945.0,
    anchor="nw",
    text="📶",
    fill="#FFFFFF",
    font=("Avenir Medium", 40 * -1),
)

canvas.create_text(
    335.9999999999999,
    951.0,
    anchor="nw",
    text="❌",
    fill="#FFFFFF",
    font=("Avenir Medium", 40 * -1),
)

image_image_12 = PhotoImage(file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(1417.0, 962.0, image=image_image_12)
window.resizable(False, False)
window.mainloop()
